module Css.Classes exposing (..)


type CssClasses
    = NavBar
    | MainLeft
    | MainRight
    | NavBarItemActive
    | NavBarCategoryContainer
    | NavBarCategory
    | NavBarRoute
    | Content
    | CryptoTabs
    | CryptoTabsActive
    | SectionLabel
    | ConfigTable
    | ConfigTableGlobalRow
    | ConfigContainer
    | TopDisplay
    | BottomDisplay
    | MultiDisplay
    | ShortCell
    | MediumCell
    | LongCell
    | TextCell
    | FormRow
    | Button
    | ButtonRow
    | Active
    | BasicInput
    | BasicInputDisabled
    | Component
    | FocusedComponent
    | InvalidComponent
    | TableButton
    | Fail
    | Success
    | StatusBar
    | InvalidGroup
    | NumberColumn
    | DirectionColumn
    | TruncatedColumn
    | DateColumn
    | TxTable
    | InputContainer
    | UnitDisplay
    | EmptyTable
    | Saving
    | Enabled
    | Disabled
    | TxDate
    | TxMachine
    | TxAmount
    | TxCrypto
    | TxPhone
    | TxAddress
