module Css.Classes exposing (..)


type CssClasses
    = NavBar
    | MainLeft
    | MainRight
    | NavBarItemActive
    | NavBarCategoryContainer
    | NavBarCategory
    | NavBarRoute
    | Content
    | CryptoTabs
    | CryptoTabsActive
    | SectionLabel
    | ConfigTable
    | ConfigTableGlobalRow
    | ConfigContainer
    | TopDisplay
    | BottomDisplay
    | MultiDisplay
    | ShortCell
    | LongCell
    | FormRow
    | Button
    | ButtonRow
    | Active
    | BasicInput
    | BasicInputDisabled
    | Component
    | FocusedComponent
    | RequiredComponent
    | TableButton
    | Fail
    | Success
    | StatusBar
    | InvalidGroup
    | NumberColumn
    | DirectionColumn
    | TruncatedColumn
    | DateColumn
    | TxTable
    | InputContainer
    | UnitDisplay
